#!/bin/bash

h=`uname -n`

if [ "$h" = "Storm.29West.Com" ]; then
    PATH=/usr/local/jdk1.6.0_02/bin:$PATH    
elif [ "$h" = "OldHat.29West.Com" ]; then
    PATH=/usr/local/jdk1.6.0_16/bin:$PATH
elif [ "$h" = "Nix.29West.Com" ]; then
    PATH=/usr/local/jdk1.6.0_16/bin:$PATH
elif [ "$h" = "raze" ]; then
    PATH=/usr/local/jdk1.6.0_10/bin/amd64:$PATH
elif [ "$h" = "Vex" ]; then
    PATH=/usr/local/jdk1.6.0_01/bin:$PATH
elif [ "$h" = "Blitz" ]; then
    PATH=/usr/local/jdk1.5.0_12/bin:$PATH
elif [ "$h" = "hack" ]; then
    PATH=/usr/local/jdk1.5.0_12/bin:$PATH
elif [ "$h" = "Hydra" ]; then
    PATH=/opt/java6/bin/IA64W:$PATH
elif [ "$h" = "Ice" ]; then
    PATH=/usr/java5_64/bin:$PATH
elif [ "$h" = "Wormwood.29West.Com" ]; then
    PATH=/usr/bin:$PATH
elif [ "$h" = "Torch.29West.Com" ]; then
    PATH=/usr/local/jdk1.6.0_16/bin:$PATH
elif [ "$h" = "Ra.29West.Com" ]; then
    PATH=/usr/local/jdk1.6.0_03/bin:$PATH
elif [ "$h" = "Day.29West.Com" ]; then
    PATH=/usr/local/jdk1.6.0/bin:$PATH
elif [ "$h" = "Jet" ]; then
    PATH=/usr/local/jdk1.5.0_12/bin:$PATH
elif [ "$h" = "Jupiter" ]; then
    PATH=/usr/bin:$PATH
elif [ "$h" = "Subzero" ]; then
    PATH=/usr/bin:$PATH
elif [ "$h" = "Blizzard" ]; then
    PATH=/usr/bin:$PATH
elif [ "$h" = "Maelstrom" ]; then
    PATH=/usr/local/java/jdk1.6.0_10/bin:$PATH
elif [ "$h" = "Phantasm" ]; then
    PATH=/usr/local/jdk1.6.0_21/bin:$PATH
elif [ "$h" = "Legend" ]; then
    PATH=/usr/bin:$PATH
elif [ "$h" = "Risk.29west.com" ]; then
    PATH=/usr/bin:$PATH
elif [ "$h" = "Saturn" ]; then
    PATH=/usr/local/jdk1.6.0_21/bin:$PATH
elif [ "$h" = "Orion" ]; then
    PATH=/usr/local/29West/jdk1.6.0_16/bin:$PATH
elif [ "$h" = "Bartender.29West.Com" ]; then
    PATH=/usr/bin:$PATH
elif [ "$h" = "Skull.29West.Com" ]; then
    PATH=/usr/java/jdk1.6.0_06/bin:$PATH
elif [ "$h" = "Crossbones.29West.Com" ]; then
    PATH=/usr/local/jdk1.6.0_06/bin:$PATH
elif [ "$h" = "Everclear.29West.Com" ]; then
    PATH=/usr/local/jdk1.6.0_06/bin:$PATH
elif [ "$h" = "Pokey" ]; then
    PATH=/usr/local/jdk1.6.0_21/bin:$PATH
elif [ "$h" = "Axe.29West.Com" ]; then
    PATH=/usr/local/jdk1.6.0_16/bin:$PATH
elif [ "$h" = "Smash.29West.Com" ]; then
    PATH=/usr/local/jdk1.6.0_16/bin:$PATH
elif [ "$h" = "Ra.29West.Com" ]; then
    PATH=/usr/local/jdk1.6.0_03/bin:$PATH
elif [ "$h" = "Vodka.29West.Com" ]; then
    PATH=/usr/local/jdk1.6.0_16/bin:$PATH
elif [ "$h" = "Gumby" ]; then
    PATH=/usr/local/jdk1.6.0_20/bin:$PATH
elif [ "$h" = "Phobos.29West.Com" ]; then
    PATH=/usr/local/jdk1.6.0_16/bin:$PATH
elif [ "$h" = "Deimos.29West.Com" ]; then
    PATH=/usr/local/jdk1.6.0_16/bin:$PATH
else
    PATH=$PATH
fi
which java
